TWEAK_NAME = Tosaka
$(TWEAK_NAME)_FILES = Tweak.xm
$(TWEAK_NAME)_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
$(TWEAK_NAME)_FRAMEWORKS += UIKit
$(TWEAK_NAME)_LIBRARIES = Togachan

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk